//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IDCliente { get; set; }
        public string NombreCliente { get; set; }
        public string ApellidosCliente { get; set; }
        public string Email { get; set; }
        public Nullable<int> TelefonoCliente { get; set; }
        public string Password { get; set; }
    }
}
