//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platos
    {
        public int platoId { get; set; }
        public string platoNombre { get; set; }
        public string platoCodigo { get; set; }
        public string platodescrip { get; set; }
        public Nullable<decimal> platoprice { get; set; }
        public Nullable<decimal> starRating { get; set; }
        public string imageUrl { get; set; }
    }
}
